- name: install cloud-init
  yum:
    name: cloud-init
    state: present
    update_cache: yes

- name: Dont upgrade on boot
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^.*package-update-upgrade-install"
    line: "# - package-update-upgrade-install"
    state: present

- name: disable auditd
  systemd:
    name: auditd
    enabled: no
