- zypper_repository:
    # contains timezone, needed by python-pytz
    repo: "https://download.opensuse.org/repositories/Cloud:/OpenStack:/Rocky/SLE_12_SP4/Cloud:OpenStack:Rocky.repo"
    state: present
    auto_import_keys: yes
    disable_gpg_check: yes

- zypper_repository:
    # contains python-pytz, needed by python-jsonschema
    repo: "https://download.opensuse.org/repositories/Virtualization:containers/SLE_12_SP4/Virtualization:containers.repo"
    state: present
    auto_import_keys: yes
    disable_gpg_check: yes

- zypper_repository:
    # contains cloud-init
    repo: "https://download.opensuse.org/repositories/Cloud:Tools/SLE_12_SP4/Cloud:Tools.repo"
    state: present
    auto_import_keys: yes
    disable_gpg_check: yes

- name: install cloud-init
  zypper:
    update_cache: yes
    disable_gpg_check: yes
    name: cloud-init
    state: present

- name: just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes
  failed_when: false
  changed_when: false
#
#- name: reload service dbus, in all cases
#  systemd:
#    name: dbus
#    state: started
#

#- name: make cloud-init start on the next boot
#  systemd:
#    name: cloud-init
#    enabled: yes
#    state: stopped
#    no_block: yes
#  failed_when: false
#  changed_when: false

- name: wait
  pause:
    minutes: 2
- name: make cloud-init start on the next boot
  systemd:
    name: cloud-init
    enabled: yes
    state: stopped
    no_block: yes



- name: Dont upgrade on boot
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^.*package-update-upgrade-install"
    line: "# - package-update-upgrade-install"
    state: present

